/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:433b1bb3-d678-4cef-9649-5591ded070d6",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_T2Pvgf4Fa",
    "aws_user_pools_web_client_id": "qj16q3hq5cmonvcgj6se4ruk2",
    "oauth": {},
    "aws_content_delivery_bucket": "awskvsreactamplified-20201005105745-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://dfmf9zz64strw.cloudfront.net"
};


export default awsmobile;
